--select * from zamow;
--select * from kontr_zamow;
--desc klient;

CREATE OR REPLACE VIEW "KONTR_ZAMOW" ("NR_KOM_ZLEC", "NR_ZLEC", "NR_ZLEC_KLI", "NR_KON", "NR_ZLEC_WEWN", "WYROZNIK", "TYP_ZLEC", "FLAG_R", "DATA_ZL", "D_POCZ_PROD", "D_ZAK_PROD", "D_PLAN", "D_WYS", "D_PL_SPED", "FORMA_WPROW", "DO_PRODUKCJI", "STATUS", "NR_ADR_DOST", "NR_KONTRAKTU", "IL_POZ", "ILE_SZYB", "ILE_M2", "WALUTA", "NR_KOMP_ROKP", "R_DAN",
                                       "NR_LISTY", "SKROT_K", "NAZ_KON", "PANSTWO", "SKROT_KRAJU", "STATUS_KONTRAH", "TYP_IFS", "NR_KONTR", "FLAG_ZAGR", "FLAG_DOD") AS 
  SELECT Z.NR_KOM_ZLEC,
 Z.NR_ZLEC,
 trim(Z.nr_zlec_kli),
 --Translate(upper(trim(Z.NR_ZLEC_KLI)),'•∆ £—”åØè','ACELNOSZZ') NR_ZLEC_KLI,
 Z.NR_KON,
 Z.NR_ZLEC_WEWN,
 Z.WYROZNIK,
 Z.TYP_ZLEC,
 Z.FLAG_R,
 Z.DATA_ZL,
 Z.D_POCZ_PROD,
 Z.D_ZAK_PROD,
 Z.D_PLAN,
 Z.D_WYS,
 Z.D_PL_SPED,
 Z.d_sped_kl,
 Z.FORMA_WPROW,
 Z.DO_PRODUKCJI,
 Z.STATUS,
 Z.NR_ADR_DOST,
 Z.NR_KONTRAKTU,
 Z.IL_POZ,
 (Z.IL_CIET+Z.I_KOM+Z.II_KOM+Z.IL_STRUKT+IL_SCH) ILE_SZYB,
 (Z.POW_C  +Z.POW_I+Z.POW_II+Z.POW_S+Z.POW_SCH) ILE_M2,
 Z.WALUTA,
 Z.NR_KOMP_ROKP,
 Z.R_DAN,
 nvl(PAMLIST.NR_LISTY,0) NR_LISTY,
 KLIENT.SKROT_K,
 KLIENT.NAZ_KON,
 KLIENT.PANSTWO,
 KRAJ.SKROT_K skrot_kraju,
 KLIENT.STATUS status_kontrah,
 KLIENT.TYP_IFS,
 KONTRAKT.NR_KONTR,
 flag_zagrozenia(Z.nr_kom_zlec, Z.forma_wprow, Z.status, Z.wyroznik, Z.flag_r, Z.d_plan, Z.d_zak_prod, Z.d_pl_sped, Z.d_sped_kl) FLAG_ZAGR,
 0 FLAG_DOD
 FROM ZAMOW Z
 LEFT JOIN KLIENT  ON Z.NR_KON=KLIENT.NR_KON
 LEFT JOIN KRAJ ON KLIENT.PANSTWO=KRAJ.PANSTWO
 LEFT  JOIN KONTRAKT ON KONTRAKT.NR_KOMP_KONTR=Z.NR_KONTRAKTU
 LEFT JOIN PAMLIST ON Z.NR_KOM_ZLEC=PAMLIST.NR_K_ZLEC
 WITH READ ONLY;
