CREATE OR REPLACE PACKAGE PKG_PARAMETRY IS
 cGR_SIL_DEFAULT CONSTANT NUMBER(2) := 4;
 cGR_SIL4 CONSTANT NUMBER(2) := 5;
 vNR_ODDZ NUMBER(2) := 0;
 FUNCTION GET_GR_SIL_DEFAULT RETURN NUMBER;
END PKG_PARAMETRY;
/

create or replace PACKAGE BODY PKG_PARAMETRY AS
 FUNCTION GET_GR_SIL_DEFAULT RETURN NUMBER AS
  BEGIN
   IF vNR_ODDZ=0 THEN 
    SELECT nr_odz INTO vNR_ODDZ FROM firma;
   END IF;
   RETURN case when vNR_ODDZ=4 THEN cGR_SIL4 else cGR_SIL_DEFAULT end;
  EXCEPTION WHEN OTHERS THEN
   RETURN -1;
  END GET_GR_SIL_DEFAULT;
END PKG_PARAMETRY;
/