CREATE UNIQUE INDEX WG_NR_KOMP_EGRUPYTOW ON "ECUTTER_GRUPYTOW" ("NR_KOMP");
CREATE UNIQUE INDEX ECUTTER_MESSAGEUSERS ON "ECUTTER_MESSAGEUSERS" ("NR_KOMP_WIAD", "NR_KOMP_KL");
CREATE UNIQUE INDEX ECUTTER_NAGRODY_WGNRKOMP ON "ECUTTER_NAGRODY" ("NR_KOMP");
CREATE   INDEX ECUTTER_NAGRODYUSERS ON "ECUTTER_NAGRODYUSERS" ("NR_KON", "NR_NAGRODY");
CREATE UNIQUE INDEX ECUTTER_PUNKTY_PK ON "ECUTTER_PUNKTY" ("NR_KON", "ROK");
CREATE UNIQUE INDEX ECUTTER_STRUCTURES_UNIQUE ON "ECUTTER_STRUCTURES" ("NR_KON", "STRUKTURA");
CREATE UNIQUE INDEX WG_IND151 ON "KODY_GRUB" ("KOD");


CREATE UNIQUE INDEX ECUTTER_SPISE_WGNRKOMP ON "ECUTTER_SPISE" ("NR_KOMP_ZLEC");
CREATE UNIQUE INDEX ECUTTER_SPISE_POZ_WGNRKOMP ON "ECUTTER_SPISE_POZ" ("NR_KOMP_ZLEC","NR_POZ");
CREATE UNIQUE INDEX WG_IND801 ON "F_POZ_POZAM" ("INDEKS");

drop table oddzialy_cent;

select * from all_objects A
where owner='EFF2020NK'
  and not exists (select 1 from user_objects O where O.object_name=A.object_name);