CREATE GLOBAL TEMPORARY TABLE "ZLECENIA_ANAL_KOSZT_TMP" 
   ("NR_ZLEC" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"NR_STRUKT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"GR_KOSZT_WYR" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"NR_KATAL_SUR" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"GR_KOSZT_SUR" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"ILOSC_SZTUK" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"SZTUK_W_OKR" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE, 
	"ILOSC_WYROBU" NUMBER(13,6) DEFAULT 0 NOT NULL ENABLE, 
	"ILOSC_SUROWCA" NUMBER(13,6) DEFAULT 0 NOT NULL ENABLE, 
	"WYDANE_W_OKR" NUMBER(13,6) DEFAULT 0 NOT NULL ENABLE, 
	"UDZIAL_W__SUR" NUMBER(13,6) DEFAULT 0 NOT NULL ENABLE, 
	"UDZIAL_W_PROD" NUMBER(13,6) DEFAULT 0 NOT NULL ENABLE, 
	"NA_RW_W_OK" NUMBER(13,6) DEFAULT 0 NOT NULL ENABLE, 
	"POMOCN" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE
   )
   ON COMMIT PRESERVE ROWS
;

CREATE UNIQUE INDEX "WG_GR_SUR_312_TMP" ON "ZLECENIA_ANAL_KOSZT_TMP" ("GR_KOSZT_SUR", "GR_KOSZT_WYR", "NR_ZLEC", "NR_STRUKT");
CREATE UNIQUE INDEX "WG_GR_WYR_312_TMP" ON "ZLECENIA_ANAL_KOSZT_TMP" ("GR_KOSZT_WYR", "GR_KOSZT_SUR", "NR_STRUKT", "NR_ZLEC");
CREATE UNIQUE INDEX "WG_ZLEC_312_TMP" ON "ZLECENIA_ANAL_KOSZT_TMP" ("NR_ZLEC", "NR_STRUKT", "GR_KOSZT_WYR", "GR_KOSZT_SUR");
